/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestingFrame.java
 *
 * Created on Jan 8, 2012, 2:00:03 PM
 */
package websiteschema.analyzer.browser.left.sample;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import org.w3c.dom.Document;
import websiteschema.analyzer.browser.utils.ClustererUtil;
import websiteschema.analyzer.context.BrowserContext;
import websiteschema.cluster.analyzer.AnalysisResult;
import websiteschema.cluster.analyzer.Doc;
import websiteschema.crawler.Crawler;
import websiteschema.crawler.WebPage;
import websiteschema.crawler.browser.BrowserWebCrawler;
import websiteschema.crawler.fb.FBDOMExtractor;
import websiteschema.crawler.fb.FBFieldFilter;
import websiteschema.crawler.htmlunit.HtmlUnitWebCrawler;
import websiteschema.element.DocumentUtil;
import websiteschema.model.domain.Websiteschema;
import websiteschema.persistence.Mapper;

/**
 *
 * @author ray
 */
public class TestingFrame extends javax.swing.JFrame {

    BrowserContext context;
    String siteId;

    /**
     * Creates new form TestingFrame
     */
    public TestingFrame() {
        initComponents();

        int screenWidth = ((int) java.awt.Toolkit.getDefaultToolkit().getScreenSize().width);
        int screenHeight = ((int) java.awt.Toolkit.getDefaultToolkit().getScreenSize().height);
        int sizeWidth = this.getWidth();
        int sizeHeight = this.getHeight();
        this.setLocation((screenWidth - sizeWidth) / 2, (screenHeight - sizeHeight) / 2);

        this.resultArea.setLineWrap(this.wrapLineCheckBox.isSelected());
        this.setTitle("测试抽取");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        startButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        clusterNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        crawlerCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        wrapLineCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        pagingCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel5 = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        startButton.setText("开始");
        startButton.setFocusable(false);
        startButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(startButton);

        jLabel3.setText("指定Cluster:");
        jToolBar1.add(jLabel3);
        jToolBar1.add(clusterNameField);

        jLabel1.setText("采集器:");
        jToolBar1.add(jLabel1);

        crawlerCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SimpleHTTPCrawler", "HtmlUnitWebCrawler", "BrowserWebCrawler" }));
        jToolBar1.add(crawlerCombo);

        jLabel2.setText("自动换行:");
        jToolBar1.add(jLabel2);

        wrapLineCheckBox.setSelected(true);
        wrapLineCheckBox.setFocusable(false);
        wrapLineCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wrapLineCheckBox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        wrapLineCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrapLineCheckBoxActionPerformed(evt);
            }
        });
        jToolBar1.add(wrapLineCheckBox);

        jLabel4.setText("自动翻页");
        jToolBar1.add(jLabel4);

        pagingCheckBox.setFocusable(false);
        pagingCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pagingCheckBox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(pagingCheckBox);

        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        jToolBar2.setRollover(true);

        jLabel5.setText("链接地址: ");
        jToolBar2.add(jLabel5);
        jToolBar2.add(urlField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        new Thread(new FooThread()).start();
    }//GEN-LAST:event_startButtonActionPerformed

    private void wrapLineCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrapLineCheckBoxActionPerformed
        // TODO add your handling code here:
        this.resultArea.setLineWrap(this.wrapLineCheckBox.isSelected());
        this.resultArea.updateUI();
    }//GEN-LAST:event_wrapLineCheckBoxActionPerformed

    public BrowserContext getContext() {
        return context;
    }

    public void setContext(BrowserContext context) {
        this.context = context;
        setUrl(context.getBrowser().getURL());
    }

    public String getSiteId() {
        return siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    public String getUrl() {
        return urlField.getText().trim();
    }

    private void setUrl(String url) {
        this.urlField.setText(url);
    }

    class FooThread implements Runnable {

        @Override
        public void run() {
            start();
        }
    };

    private WebPage crawl(String url) {
        if (null != url) {
            this.setTitle("测试抽取: " + url);
            context.getConsole().log("开始采集：" + url);
            this.resultArea.setText("开始采集：" + url + "\n");
            Crawler crawler = null;
            if ("HtmlUnitWebCrawler".equals(getCrawler())) {
                HtmlUnitWebCrawler huwc = new HtmlUnitWebCrawler();
                huwc.setJavaScriptEnabled(true);
                crawler = huwc;
            } else if ("BrowserWebCrawler".equals(getCrawler())) {
                BrowserWebCrawler bwc = new BrowserWebCrawler();
                bwc.setAllowPopupWindow(false);
                crawler = bwc;
            } else {
                crawler = new websiteschema.crawler.SimpleHttpCrawler();
            }
            long t1 = System.currentTimeMillis();
            WebPage page = crawler.crawlWebPage(url);
            long t2 = System.currentTimeMillis();
            context.getConsole().log("采集结束，耗时：" + (t2 - t1));
            this.resultArea.append("采集结束，耗时：" + (t2 - t1) + "\n");
            return page;
        } else {
            return null;
        }
    }

    private String getDocumentBelongToCluster(Document source) {
        String clusterName = this.clusterNameField.getText();
        if (null != clusterName && !"".equals(clusterName)) {
            clusterName = clusterName.trim();
        } else {
            context.getConsole().log("开始分类");
            this.resultArea.append("开始分类\n");
            clusterName = ClustererUtil.getInstance().classify(getSiteId(), source);
            if (null == clusterName) {
                clusterName = AnalysisResult.DefaultClusterName;
            }
            context.getConsole().log("此页面属于类：" + clusterName);
            this.resultArea.append("此页面属于类：" + clusterName + "\n");
            this.clusterNameField.setText(clusterName);
        }
        return clusterName;
    }

    private Doc extractDocument(Websiteschema websiteschema, String clusterName, WebPage page, boolean paging) {
        FBDOMExtractor extractor = new FBDOMExtractor();
        extractor.page = page;
        extractor.schema = websiteschema;
        extractor.clusterName = clusterName;
        extractor.paging = paging;
        context.getConsole().log("开始尝试抽取页面：");
        this.resultArea.append("开始尝试抽取页面：\n");
        extractor.extract();
        context.getConsole().log("抽取结束：");
        Doc result = extractor.out;
        return result;
    }

    private Doc filteringDocument(Doc orig) {
        Map<String, String> fields = new HashMap<String, String>();
        fields.put("SOURCENAME", "websiteschema.cluster.analyzer.fields.SourceNameFilter");
        fields.put("AUTHOR", "com.apc.websiteschema.cluster.fields.AuthorFilter");
        FBFieldFilter filter = new FBFieldFilter();
        filter.doc = orig;
        filter.filters = fields;
        filter.filtering();
        return filter.doc;
    }

    private void start() {
        this.startButton.setEnabled(false);
        try {
            Mapper<Websiteschema> mapper = BrowserContext.getSpringContext().getBean("websiteschemaMapper", Mapper.class);
            Websiteschema websiteschema = mapper.get(getSiteId());
            //采集指定URL
            WebPage page = crawl(getUrl());

            if (null != page) {
                //为采集到的文档进行分类
                Document source = null != page ? page.getDocs()[0] : (Document) (context.getBrowser().getW3CDocument());
                String clusterName = getDocumentBelongToCluster(source);
                //抽取文档
                Doc result = extractDocument(websiteschema, clusterName, page, pagingCheckBox.isSelected());
                //对某些参数进行过滤
                result = filteringDocument(result);
                //对结果进行输出
                if (null != result) {
                    this.resultArea.setText(DocumentUtil.getXMLString(result.toW3CDocument()));
                } else {
                    JOptionPane.showMessageDialog(this, "无法抽取出数据！");
                }
            } else {
                JOptionPane.showMessageDialog(this, "抽取页面异常");
            }
        } finally {
            this.startButton.setEnabled(true);
        }
    }

    private String getCrawler() {
        return this.crawlerCombo.getSelectedItem().toString();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clusterNameField;
    private javax.swing.JComboBox crawlerCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JCheckBox pagingCheckBox;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField urlField;
    private javax.swing.JCheckBox wrapLineCheckBox;
    // End of variables declaration//GEN-END:variables
}
