/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DOMPanel.java
 *
 * Created on Feb 29, 2012, 3:03:16 PM
 */
package websiteschema.analyzer.browser.bottom.domtree;

import com.sun.webkit.dom.HTMLElementImpl;
import com.webrenderer.swing.dom.IDocument;
import com.webrenderer.swing.dom.IElement;
import org.w3c.dom.Document;

import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;

/**
 *
 * @author ray
 */
public class DOMPanel extends javax.swing.JPanel {

    DOMTree domTree = null;

    /** Creates new form DOMPanel */
    public DOMPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setupDOMTree(Document block) {
        if (null == block) {
            return;
        }
        if (null != domTree) {
            domTree.removeAll();
            domTree.setModel(new DOMTreeModel(new DOMTreeNode((com.sun.webkit.dom.HTMLElementImpl) block.getDocumentElement())));
        } else {
            domTree = new DOMTree((com.sun.webkit.dom.HTMLElementImpl) block.getDocumentElement());
            getScrollPane().setViewportView(domTree);
            domTree.addTreeSelectionListener((TreeSelectionListener) new TreeSelectionListener() {

                private DOMTreeNode lastSelectedVB = null;
//                private String style = "border-style: solid; border-width: 5px; border-color: black;";
                private String style = "background-color: LightSteelBlue;";

                @Override
                public void valueChanged(TreeSelectionEvent e) {
                    System.out.println("selected " + e.getPath());
                    DOMTreeNode vb = (DOMTreeNode) e.getPath().getLastPathComponent();
//                    drawRectangleInPage(vb.getEle());
                    undraw(lastSelectedVB);
                    draw(vb);
                    lastSelectedVB = vb;
                }

                private void draw(DOMTreeNode ele) {
                    if (null != ele) {
                        draw(ele.getEle());
                    }
                }

                private void undraw(DOMTreeNode ele) {
                    if (null != ele) {
                        undraw(ele.getEle());
                    }
                }

                private void draw(HTMLElementImpl ele) {
                    if (null != ele) {
                        String oldStyle = ele.getAttribute("style");
                        if (null != oldStyle && !"".equals(oldStyle)) {
                            ele.setAttribute("style", oldStyle + ";" + style);
                        } else {
                            ele.setAttribute("style", style);
                        }
                    }
                }

                private void undraw(HTMLElementImpl ele) {
                    if (null != ele) {
                        String oldStyle = ele.getAttribute("style");
                        if (null != oldStyle && !"".equals(oldStyle)) {
                            String s = oldStyle.replaceAll(style, "");
                            ele.setAttribute("style", s);
                        }
                    }
                }
            });
        }


    }

    public javax.swing.JScrollPane getScrollPane() {
        return jScrollPane1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
